from typing import Protocol
from datetime import datetime


class GitRepository(Protocol):
    def commit_count(self) -> int: ...
    def first_commit_date(self) -> datetime | None: ...
    def last_commit_date(self) -> datetime | None: ...
