from typing import Protocol
from datetime import datetime

from git_xrays.domain.models import FileChange


class GitRepository(Protocol):
    def commit_count(self) -> int: ...
    def first_commit_date(self) -> datetime | None: ...
    def last_commit_date(self) -> datetime | None: ...
    def file_changes(
        self, since: datetime | None = None, until: datetime | None = None
    ) -> list[FileChange]: ...
    def resolve_ref(self, ref: str) -> datetime: ...
    def file_sizes(self, ref: str | None = None) -> dict[str, int]: ...


class SourceCodeReader(Protocol):
    def list_python_files(self, ref: str | None = None) -> list[str]: ...
    def read_file(self, file_path: str, ref: str | None = None) -> str: ...
